#!/usr/bin/bash

USER=$(id -nu 1000)
HOME=$(getent passwd $USER | cut -d: -f6)

# SteamOS lightdm config
CONF_FILE='/etc/lightdm/lightdm.conf.d/00-autologin-user.conf'
AUTOLOGIN_CONF='/etc/lightdm/lightdm.conf.d/10-gamescope-session.conf'

# Configure autologin if Steam has been updated
if [ -f $HOME/.local/share/Steam/ubuntu12_32/steamui.so ]; then
  sed -i 's/.*autologin-session=.*/autologin-session=gamescope-session/g' ${AUTOLOGIN_CONF}
else
  sed -i 's/.*autologin-session=.*/autologin-session=gnome-wayland/g' ${AUTOLOGIN_CONF}
fi
sed -i 's/.*autologin-user=.*/autologin-user='${USER}'/g' ${CONF_FILE}
